provider:
  name: faas
  gateway: http://localhost:8080  # can be a remote server

functions:
  derek:
    handler: ./derek
    image: derek
    lang: Dockerfile
    environment:
      application: <your_GH_applicationID>
      validate_hmac: true
      debug: true
    secrets:
      - derek-secret-key
      - derek-private-key
