name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build-Test
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: make build
      - name: Test
        run: make test
